### ISSUE TITLE
any reason for being that specific about the node version?

### ISSUE THREAD

**Issue by st-h** [mirego/ember-best-language#12]
If I understand correctly, the version 1.0.0 of this add on requires node version 10.14.1

https://github.com/mirego/ember-best-language/blob/e5929e313e95a02bc2a65da7ee89cc7a076151ad/package.json#L80

When using a different version, this leads to the following error when trying to install/upgrade the addon:

`error ember-best-language@1.0.0: The engine "node" is incompatible with this module. Expected version "10.14.1". Got "11.3.0"`

Previous versions of this add-on were more relaxed regarding this requirement. Is there a reason for the change?

If there isn't any specific reason, using what ember itself is using, probably might make sense to improve compatibility:
` "engines": {
    "node": "6.* || 8.* || >= 10.*"
  },`

**Comment by charlesdemers** [comment]
Hey! We froze it to make sure in everyone working on the addon had the same version, never thought this would be enforced when installing the addon as a dependency… 😬 

I just released v1.0.1 to fix this, enjoy and thanks for reporting the issue!
