### ISSUE TITLE
Could not find module `@ember-decorators/object` imported from `ember-best-language/services/best-language`

### ISSUE THREAD

**Issue by st-h** [mirego/ember-best-language#13]
Thank your for the fast fix regarding the node version. After installing I am seeing the following error in the browser at runtime:

```
Uncaught Error: Could not find module `@ember-decorators/object` imported from `ember-best-language/services/best-language`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:422)
    at Class.resolveOther (index.js:101)
    at Class.resolve (index.js:163)
```

I am unfamiliar with ember-decorators, but probably you need to move it to the dependencies section of package.json. I had a quick look at [some other add ons that are using ember-decorators](https://www.npmjs.com/browse/depended/ember-decorators) and this seems to be the case. For instance:
https://github.com/miguelcobain/ember-yeti-table/blob/master/package.json

**Comment by charlesdemers** [comment]
Sorry about that, we use decorators at Mirego so I never hit that problem, I released 1.0.3 with `ember-decorators` stuff in `dependencies` That should fix your issue and again, thank you for reporting!

**Comment by catz** [comment]
Hello Charles,

Tried to update to 1.0.3 and started to get this warning on start: 'WARNING: The 'ember-best-language' addon is using an older version of ember-cli-typescript that uses stage 1 decorators. Please update to ember-cli-typescript@v2 to remove your dependency on legacy decorators.'

I neither use ember-cli-typescript nor decorators in the project.

Any ideas? Thank you.

**Comment by charlesdemers** [comment]
Hey @catz, `ember-best-language` uses both TypeScript and decorators that’s why the message is appearing. This is a bit annoying for us because `ember-cli-typescript` v2 is still in beta, so we don't want to update right away… I don’t know why they prompt users to update to an unstable version 🤔 

Anyway, rest assured that we'll update the addon to v2 as soon as it's released as a "stable" version!
