### ISSUE TITLE
Blank page with using ember-best-language on Ember 3.12.0

### ISSUE THREAD

**Issue by alex-kovalchuk** [mirego/ember-best-language#31]
After updating the application from Ember 3.10.1 to 3.12.0, it began to give a blank page. After a long search, I found the reason. With ember-best-language, the application gives a blank page while there are no errors in the console.
The extension in the Ember Inspector browser also stops detecting the application.

node: 10.16.3
npm: 6.11.2
ember-cli: 3.12.0
ember-cli-fastboot: 2.1.3
ember-best-language: 1.0.6 or 1.0.7

Thanks!

**Comment by scottkidder** [comment]
I can confirm this. This was a real pain to track down. For me with fastboot in dev it would sometimes render the app but then lose all interactivity.

**Comment by scottkidder** [comment]
Looked into this and found that v1.0.4 still works and v1.0.5 and after is broken.

**Comment by charlesdemers** [comment]
Looks like a dependency update broke something :\ I’m sorry you’re having trouble with this, I’ll take a look at this in the coming days and come back with a fix unless you find a solution before me!

**Comment by scottkidder** [comment]
@charlesdemers I believe I've found the issue [here](https://github.com/mirego/ember-best-language/blob/master/config/environment.js#L6). Looks like the bad comparison was causing host apps to end up with `autoboot: false`.

**Comment by scottkidder** [comment]
The only troubling thing here is how difficult this was to track down. :confused:

**Comment by charlesdemers** [comment]
Thanks for figuring this out @scottkidder!

It's a shame we can't convert that file to TypeScript, it would've caught it instantly…

**Comment by charlesdemers** [comment]
Version 1.0.8 is published with the fix, thanks again!

**Comment by scottkidder** [comment]
Thanks for getting it out there! Cheers!
