### ISSUE TITLE
Loosen required versions dependencies

### ISSUE THREAD

**Issue by scottkidder** [mirego/ember-best-language#34]
Is there any opposition to un-'pinning' the versions of both `ember-cli-babel` and `ember-cli-typescript`? I think adding a `^` is fairly safe given the stability and ubiquity of these two addons. It prevents people from having to do their own `resolutions` configuration to stay on the latest versions of these dependencies.

**Comment by charlesdemers** [comment]
Hey @scottkidder I released v2.0.1 with up-to-date dependencies and unpinned version of `ember-cli-babel` and `ember-cli-typescript`. Cheers!

**Comment by scottkidder** [comment]
Thanks @charlesdemers. Cheers!
