### ISSUE TITLE
support an array of language codes with country code

### ISSUE THREAD

**Issue by 0xadada** [mirego/ember-best-language#7]
Implement support for `bestLanguage` function to accept an array of language codes, each of which can (optionally) include a hyphen `-` AND an [ISO 3166-1 region code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)

https://github.com/mirego/ember-best-language/blob/master/addon/services/best-language.js#L10

**Comment by charlesdemers** [comment]
Fixed by #9

**Comment by 0xadada** [comment]
👏
